import * as React from 'react';
import Head from 'next/head';

import { AppBar, Typography } from '@mui/material';

import Header from './Header';

interface Props {
    children?: React.ReactNode;
}

export const Layout: React.FC<Props> = (props) => {

    return (
        <div>
            <Head>
                <title>Create T3 App</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className='content-body'>
                <Header />
                {props.children}
            </main>
        </div>
    )
}

export default Layout;